"""Register the launcher with Chrome so the extension can start the server.

Run once:  uv run python launcher/install.py
Undo with: uv run python launcher/install.py --uninstall
"""

import base64
import hashlib
import json
import shlex
import stat
import sys
from pathlib import Path

HOST_NAME = "com.videosummarizer.launcher"
LAUNCHER_DIR = Path(__file__).resolve().parent
PROJECT_DIR = LAUNCHER_DIR.parent
EXTENSION_DIR = PROJECT_DIR / "extension"
CHROME_HOSTS_DIR = Path.home() / "Library/Application Support/Google/Chrome/NativeMessagingHosts"
HOST_SCRIPT = Path.home() / "Library/Application Support/VideoSummarizer/host.sh"
HOST_LOG = Path.home() / "Library/Logs/VideoSummarizer/host.log"

HOST_TEMPLATE = """#!/bin/sh
# Generated by launcher/install.py. Chrome runs this when the extension button is clicked.
LOG={log}
mkdir -p "$(dirname "$LOG")"
echo "$(date '+%Y-%m-%d %H:%M:%S') started by $1" >> "$LOG"
exec {python} {host} "$@" 2>> "$LOG"
"""


def extension_id() -> str:
    """Chrome derives an extension's ID from the public key in its manifest."""
    key = json.loads((EXTENSION_DIR / "manifest.json").read_text())["key"]
    digest = hashlib.sha256(base64.b64decode(key)).hexdigest()[:32]
    return "".join(chr(ord("a") + int(c, 16)) for c in digest)


def main() -> None:
    manifest_path = CHROME_HOSTS_DIR / f"{HOST_NAME}.json"

    if "--uninstall" in sys.argv:
        manifest_path.unlink(missing_ok=True)
        HOST_SCRIPT.unlink(missing_ok=True)
        print(f"Removed {manifest_path} and {HOST_SCRIPT}")
        return

    # The script Chrome runs lives outside the project folder: if the project is in a
    # privacy-protected folder (Documents, Desktop, ...) macOS may block Chrome from reading
    # it, and a script there couldn't even start to report the problem.
    python = PROJECT_DIR / ".venv/bin/python"
    HOST_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    HOST_SCRIPT.write_text(HOST_TEMPLATE.format(
        log=shlex.quote(str(HOST_LOG)),
        python=shlex.quote(str(python)),
        host=shlex.quote(str(LAUNCHER_DIR / "native_host.py")),
    ))
    HOST_SCRIPT.chmod(HOST_SCRIPT.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    host = HOST_SCRIPT

    ext_id = extension_id()
    CHROME_HOSTS_DIR.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({
        "name": HOST_NAME,
        "description": "Starts the local Video Summarizer server",
        "path": str(host),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{ext_id}/"],
    }, indent=2))

    print(f"Registered the launcher with Chrome: {manifest_path}")
    print(f"Extension ID: {ext_id}\n")
    print("Next, load the extension in Chrome:")
    print("  1. Open chrome://extensions")
    print("  2. Turn on 'Developer mode' (top right)")
    print(f"  3. Click 'Load unpacked' and choose: {EXTENSION_DIR}")
    print("  4. Pin 'Video Summarizer' from the puzzle-piece menu so the button is always visible")


if __name__ == "__main__":
    main()
